# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gerix_gui4.ui'
#
# Created: Tue Jan 29 02:28:33 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Main_window(object):
    def setupUi(self, Main_window):
        Main_window.setObjectName(_fromUtf8("Main_window"))
        Main_window.setEnabled(True)
        Main_window.resize(648, 642)
        self.widget = QtGui.QWidget(Main_window)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridlayout = QtGui.QGridLayout(self.widget)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.pixmapLabel1 = QtGui.QLabel(self.widget)
        self.pixmapLabel1.setPixmap(QtGui.QPixmap(_fromUtf8("gerix.png")))
        self.pixmapLabel1.setScaledContents(True)
        self.pixmapLabel1.setWordWrap(False)
        self.pixmapLabel1.setObjectName(_fromUtf8("pixmapLabel1"))
        self.gridlayout.addWidget(self.pixmapLabel1, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(61, 31, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.text_output = QtGui.QTextEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_output.sizePolicy().hasHeightForWidth())
        self.text_output.setSizePolicy(sizePolicy)
        self.text_output.setMaximumSize(QtCore.QSize(32767, 100))
        self.text_output.setReadOnly(True)
        self.text_output.setProperty("text", _fromUtf8(""))
        self.text_output.setObjectName(_fromUtf8("text_output"))
        self.gridlayout.addWidget(self.text_output, 1, 0, 1, 3)
        self.tabWidget2 = QtGui.QTabWidget(self.widget)
        self.tabWidget2.setObjectName(_fromUtf8("tabWidget2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridlayout1 = QtGui.QGridLayout(self.tab)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.pixmapLabel2 = QtGui.QLabel(self.tab)
        self.pixmapLabel2.setPixmap(QtGui.QPixmap(_fromUtf8("gerix_wifi_cracker.png")))
        self.pixmapLabel2.setScaledContents(True)
        self.pixmapLabel2.setWordWrap(False)
        self.pixmapLabel2.setObjectName(_fromUtf8("pixmapLabel2"))
        self.gridlayout1.addWidget(self.pixmapLabel2, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(101, 41, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 0, 2, 1, 1)
        self.textLabel1 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel1.sizePolicy().hasHeightForWidth())
        self.textLabel1.setSizePolicy(sizePolicy)
        self.textLabel1.setMinimumSize(QtCore.QSize(600, 0))
        self.textLabel1.setMouseTracking(True)
        self.textLabel1.setTextFormat(QtCore.Qt.AutoText)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.gridlayout1.addWidget(self.textLabel1, 1, 0, 1, 3)
        self.tabWidget2.addTab(self.tab, _fromUtf8(""))
        self.TabPage = QtGui.QWidget()
        self.TabPage.setObjectName(_fromUtf8("TabPage"))
        self.gridlayout2 = QtGui.QGridLayout(self.TabPage)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.toolBox3_2 = QtGui.QToolBox(self.TabPage)
        self.toolBox3_2.setObjectName(_fromUtf8("toolBox3_2"))
        self.page1 = QtGui.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 440, 330))
        self.page1.setObjectName(_fromUtf8("page1"))
        self.gridlayout3 = QtGui.QGridLayout(self.page1)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.button_reload_interfaces = QtGui.QPushButton(self.page1)
        self.button_reload_interfaces.setObjectName(_fromUtf8("button_reload_interfaces"))
        self.hboxlayout.addWidget(self.button_reload_interfaces)
        self.button_random_mac = QtGui.QPushButton(self.page1)
        self.button_random_mac.setObjectName(_fromUtf8("button_random_mac"))
        self.hboxlayout.addWidget(self.button_random_mac)
        self.button_monitor = QtGui.QPushButton(self.page1)
        self.button_monitor.setObjectName(_fromUtf8("button_monitor"))
        self.hboxlayout.addWidget(self.button_monitor)
        self.gridlayout3.addLayout(self.hboxlayout, 3, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.textLabel1_2 = QtGui.QLabel(self.page1)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName(_fromUtf8("textLabel1_2"))
        self.hboxlayout1.addWidget(self.textLabel1_2)
        self.combo_channel = QtGui.QComboBox(self.page1)
        self.combo_channel.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_channel.setObjectName(_fromUtf8("combo_channel"))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.combo_channel.addItem(_fromUtf8(""))
        self.hboxlayout1.addWidget(self.combo_channel)
        self.textLabel2_4 = QtGui.QLabel(self.page1)
        self.textLabel2_4.setWordWrap(False)
        self.textLabel2_4.setObjectName(_fromUtf8("textLabel2_4"))
        self.hboxlayout1.addWidget(self.textLabel2_4)
        self.spin_sec = QtGui.QSpinBox(self.page1)
        self.spin_sec.setMinimum(5)
        self.spin_sec.setMaximum(200)
        self.spin_sec.setProperty("value", 10)
        self.spin_sec.setObjectName(_fromUtf8("spin_sec"))
        self.hboxlayout1.addWidget(self.spin_sec)
        self.button_rescan_networks = QtGui.QPushButton(self.page1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_rescan_networks.sizePolicy().hasHeightForWidth())
        self.button_rescan_networks.setSizePolicy(sizePolicy)
        self.button_rescan_networks.setObjectName(_fromUtf8("button_rescan_networks"))
        self.hboxlayout1.addWidget(self.button_rescan_networks)
        self.gridlayout3.addLayout(self.hboxlayout1, 6, 0, 1, 1)
        self.textLabel3_5_6_2_2 = QtGui.QLabel(self.page1)
        self.textLabel3_5_6_2_2.setWordWrap(False)
        self.textLabel3_5_6_2_2.setObjectName(_fromUtf8("textLabel3_5_6_2_2"))
        self.gridlayout3.addWidget(self.textLabel3_5_6_2_2, 1, 0, 1, 1)
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setObjectName(_fromUtf8("gridlayout4"))
        self.textLabel3_4_4 = QtGui.QLabel(self.page1)
        self.textLabel3_4_4.setWordWrap(False)
        self.textLabel3_4_4.setObjectName(_fromUtf8("textLabel3_4_4"))
        self.gridlayout4.addWidget(self.textLabel3_4_4, 0, 0, 1, 2)
        self.line_gath_logs = QtGui.QLineEdit(self.page1)
        self.line_gath_logs.setObjectName(_fromUtf8("line_gath_logs"))
        self.gridlayout4.addWidget(self.line_gath_logs, 1, 0, 1, 1)
        self.button_gath_clean = QtGui.QPushButton(self.page1)
        self.button_gath_clean.setObjectName(_fromUtf8("button_gath_clean"))
        self.gridlayout4.addWidget(self.button_gath_clean, 1, 1, 1, 1)
        self.gridlayout3.addLayout(self.gridlayout4, 0, 0, 1, 1)
        self.textLabel3_5_6_2 = QtGui.QLabel(self.page1)
        self.textLabel3_5_6_2.setWordWrap(False)
        self.textLabel3_5_6_2.setObjectName(_fromUtf8("textLabel3_5_6_2"))
        self.gridlayout3.addWidget(self.textLabel3_5_6_2, 4, 0, 1, 1)
        self.table_interfaces = QtGui.QTableWidget(self.page1)
        self.table_interfaces.setMinimumSize(QtCore.QSize(0, 85))
        self.table_interfaces.setMaximumSize(QtCore.QSize(5000, 100))
        self.table_interfaces.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.table_interfaces.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_interfaces.setShowGrid(False)
        self.table_interfaces.setWordWrap(False)
        self.table_interfaces.setRowCount(2)
        self.table_interfaces.setColumnCount(5)
        self.table_interfaces.setObjectName(_fromUtf8("table_interfaces"))
        item = QtGui.QTableWidgetItem()
        self.table_interfaces.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_interfaces.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_interfaces.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_interfaces.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_interfaces.setHorizontalHeaderItem(4, item)
        self.table_interfaces.horizontalHeader().setVisible(False)
        self.table_interfaces.verticalHeader().setVisible(False)
        self.table_interfaces.verticalHeader().setDefaultSectionSize(20)
        self.table_interfaces.verticalHeader().setHighlightSections(True)
        self.gridlayout3.addWidget(self.table_interfaces, 2, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.page1)
        self.tableWidget.setMaximumSize(QtCore.QSize(5000, 5000))
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridlayout3.addWidget(self.tableWidget, 5, 0, 1, 1)
        self.toolBox3_2.addItem(self.page1, _fromUtf8(""))
        self.gridlayout2.addWidget(self.toolBox3_2, 0, 0, 1, 1)
        self.tabWidget2.addTab(self.TabPage, _fromUtf8(""))
        self.TabPage1 = QtGui.QWidget()
        self.TabPage1.setObjectName(_fromUtf8("TabPage1"))
        self.gridlayout5 = QtGui.QGridLayout(self.TabPage1)
        self.gridlayout5.setObjectName(_fromUtf8("gridlayout5"))
        self.toolBox2_2 = QtGui.QToolBox(self.TabPage1)
        self.toolBox2_2.setObjectName(_fromUtf8("toolBox2_2"))
        self.page11 = QtGui.QWidget()
        self.page11.setGeometry(QtCore.QRect(0, 0, 174, 91))
        self.page11.setObjectName(_fromUtf8("page11"))
        self._2 = QtGui.QVBoxLayout(self.page11)
        self._2.setObjectName(_fromUtf8("_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.button_wep_start_sniff = QtGui.QPushButton(self.page11)
        self.button_wep_start_sniff.setObjectName(_fromUtf8("button_wep_start_sniff"))
        self.verticalLayout.addWidget(self.button_wep_start_sniff)
        self._2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 12, -1, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.button_wep_test_inj = QtGui.QPushButton(self.page11)
        self.button_wep_test_inj.setObjectName(_fromUtf8("button_wep_test_inj"))
        self.verticalLayout_2.addWidget(self.button_wep_test_inj)
        self._2.addLayout(self.verticalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(41, 110, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._2.addItem(spacerItem4)
        self.toolBox2_2.addItem(self.page11, _fromUtf8(""))
        self.page2 = QtGui.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 351, 292))
        self.page2.setObjectName(_fromUtf8("page2"))
        self.gridlayout6 = QtGui.QGridLayout(self.page2)
        self.gridlayout6.setObjectName(_fromUtf8("gridlayout6"))
        spacerItem5 = QtGui.QSpacerItem(41, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout6.addItem(spacerItem5, 5, 0, 1, 1)
        self.verticalGroupBox_3 = QtGui.QGroupBox(self.page2)
        self.verticalGroupBox_3.setObjectName(_fromUtf8("verticalGroupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.button_wep_fake_auth_chop = QtGui.QPushButton(self.verticalGroupBox_3)
        self.button_wep_fake_auth_chop.setObjectName(_fromUtf8("button_wep_fake_auth_chop"))
        self.verticalLayout_3.addWidget(self.button_wep_fake_auth_chop)
        self.button_wep_start_chop = QtGui.QPushButton(self.verticalGroupBox_3)
        self.button_wep_start_chop.setObjectName(_fromUtf8("button_wep_start_chop"))
        self.verticalLayout_3.addWidget(self.button_wep_start_chop)
        self.button_wep_create_arp_chop = QtGui.QPushButton(self.verticalGroupBox_3)
        self.button_wep_create_arp_chop.setObjectName(_fromUtf8("button_wep_create_arp_chop"))
        self.verticalLayout_3.addWidget(self.button_wep_create_arp_chop)
        self.button_wep_arp_inj_chop = QtGui.QPushButton(self.verticalGroupBox_3)
        self.button_wep_arp_inj_chop.setObjectName(_fromUtf8("button_wep_arp_inj_chop"))
        self.verticalLayout_3.addWidget(self.button_wep_arp_inj_chop)
        self.gridlayout6.addWidget(self.verticalGroupBox_3, 0, 0, 1, 1)
        self.verticalGroupBox_4 = QtGui.QGroupBox(self.page2)
        self.verticalGroupBox_4.setObjectName(_fromUtf8("verticalGroupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalGroupBox_4)
        self.verticalLayout_4.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.button_wep_assoc_fake_auth_frag = QtGui.QPushButton(self.verticalGroupBox_4)
        self.button_wep_assoc_fake_auth_frag.setObjectName(_fromUtf8("button_wep_assoc_fake_auth_frag"))
        self.verticalLayout_4.addWidget(self.button_wep_assoc_fake_auth_frag)
        self.button_wep_start_frag = QtGui.QPushButton(self.verticalGroupBox_4)
        self.button_wep_start_frag.setObjectName(_fromUtf8("button_wep_start_frag"))
        self.verticalLayout_4.addWidget(self.button_wep_start_frag)
        self.button_wep_create_arp_frag = QtGui.QPushButton(self.verticalGroupBox_4)
        self.button_wep_create_arp_frag.setObjectName(_fromUtf8("button_wep_create_arp_frag"))
        self.verticalLayout_4.addWidget(self.button_wep_create_arp_frag)
        self.button_wep_arp_inj_frag = QtGui.QPushButton(self.verticalGroupBox_4)
        self.button_wep_arp_inj_frag.setObjectName(_fromUtf8("button_wep_arp_inj_frag"))
        self.verticalLayout_4.addWidget(self.button_wep_arp_inj_frag)
        self.gridlayout6.addWidget(self.verticalGroupBox_4, 4, 0, 1, 1)
        self.toolBox2_2.addItem(self.page2, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 208, 402))
        self.page.setObjectName(_fromUtf8("page"))
        self.vboxlayout = QtGui.QVBoxLayout(self.page)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.verticalGroupBox_5 = QtGui.QGroupBox(self.page)
        self.verticalGroupBox_5.setObjectName(_fromUtf8("verticalGroupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalGroupBox_5)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.button_wep_assoc_fake_auth_rep = QtGui.QPushButton(self.verticalGroupBox_5)
        self.button_wep_assoc_fake_auth_rep.setObjectName(_fromUtf8("button_wep_assoc_fake_auth_rep"))
        self.verticalLayout_5.addWidget(self.button_wep_assoc_fake_auth_rep)
        self.button_wep_start_rep = QtGui.QPushButton(self.verticalGroupBox_5)
        self.button_wep_start_rep.setObjectName(_fromUtf8("button_wep_start_rep"))
        self.verticalLayout_5.addWidget(self.button_wep_start_rep)
        self.vboxlayout.addWidget(self.verticalGroupBox_5)
        self.verticalGroupBox_6 = QtGui.QGroupBox(self.page)
        self.verticalGroupBox_6.setObjectName(_fromUtf8("verticalGroupBox_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalGroupBox_6)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.button_wep_assoc_fake_auth_req = QtGui.QPushButton(self.verticalGroupBox_6)
        self.button_wep_assoc_fake_auth_req.setObjectName(_fromUtf8("button_wep_assoc_fake_auth_req"))
        self.verticalLayout_6.addWidget(self.button_wep_assoc_fake_auth_req)
        self.textLabel7_2 = QtGui.QLabel(self.verticalGroupBox_6)
        self.textLabel7_2.setWordWrap(False)
        self.textLabel7_2.setObjectName(_fromUtf8("textLabel7_2"))
        self.verticalLayout_6.addWidget(self.textLabel7_2)
        self.spin_wep_wired_req = QtGui.QSpinBox(self.verticalGroupBox_6)
        self.spin_wep_wired_req.setMaximum(90000)
        self.spin_wep_wired_req.setProperty("value", 86)
        self.spin_wep_wired_req.setObjectName(_fromUtf8("spin_wep_wired_req"))
        self.verticalLayout_6.addWidget(self.spin_wep_wired_req)
        self.spin_wep_wireless_req = QtGui.QSpinBox(self.verticalGroupBox_6)
        self.spin_wep_wireless_req.setMaximum(90000)
        self.spin_wep_wireless_req.setProperty("value", 68)
        self.spin_wep_wireless_req.setObjectName(_fromUtf8("spin_wep_wireless_req"))
        self.verticalLayout_6.addWidget(self.spin_wep_wireless_req)
        self.textLabel6_3 = QtGui.QLabel(self.verticalGroupBox_6)
        self.textLabel6_3.setWordWrap(False)
        self.textLabel6_3.setObjectName(_fromUtf8("textLabel6_3"))
        self.verticalLayout_6.addWidget(self.textLabel6_3)
        self.button_wep_capture_req = QtGui.QPushButton(self.verticalGroupBox_6)
        self.button_wep_capture_req.setObjectName(_fromUtf8("button_wep_capture_req"))
        self.verticalLayout_6.addWidget(self.button_wep_capture_req)
        self.vboxlayout.addWidget(self.verticalGroupBox_6)
        self.verticalGroupBox_7 = QtGui.QGroupBox(self.page)
        self.verticalGroupBox_7.setObjectName(_fromUtf8("verticalGroupBox_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalGroupBox_7)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.textLabel6_2_2 = QtGui.QLabel(self.verticalGroupBox_7)
        self.textLabel6_2_2.setWordWrap(False)
        self.textLabel6_2_2.setObjectName(_fromUtf8("textLabel6_2_2"))
        self.verticalLayout_7.addWidget(self.textLabel6_2_2)
        self.combo_wep_mac_cfrag = QtGui.QComboBox(self.verticalGroupBox_7)
        self.combo_wep_mac_cfrag.setEditable(True)
        self.combo_wep_mac_cfrag.setObjectName(_fromUtf8("combo_wep_mac_cfrag"))
        self.verticalLayout_7.addWidget(self.combo_wep_mac_cfrag)
        self.button_wep_autoload_clients_cfrag = QtGui.QPushButton(self.verticalGroupBox_7)
        self.button_wep_autoload_clients_cfrag.setObjectName(_fromUtf8("button_wep_autoload_clients_cfrag"))
        self.verticalLayout_7.addWidget(self.button_wep_autoload_clients_cfrag)
        self.button_wep_arp_inj_cfrag = QtGui.QPushButton(self.verticalGroupBox_7)
        self.button_wep_arp_inj_cfrag.setObjectName(_fromUtf8("button_wep_arp_inj_cfrag"))
        self.verticalLayout_7.addWidget(self.button_wep_arp_inj_cfrag)
        self.vboxlayout.addWidget(self.verticalGroupBox_7)
        spacerItem6 = QtGui.QSpacerItem(41, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem6)
        self.toolBox2_2.addItem(self.page, _fromUtf8(""))
        self.page1 = QtGui.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 228, 204))
        self.page1.setObjectName(_fromUtf8("page1"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.page1)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.groupBox_3 = QtGui.QGroupBox(self.page1)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.button_wep_start_latte = QtGui.QPushButton(self.groupBox_3)
        self.button_wep_start_latte.setObjectName(_fromUtf8("button_wep_start_latte"))
        self.verticalLayout_11.addWidget(self.button_wep_start_latte)
        self.vboxlayout1.addWidget(self.groupBox_3)
        self.verticalGroupBox_8 = QtGui.QGroupBox(self.page1)
        self.verticalGroupBox_8.setObjectName(_fromUtf8("verticalGroupBox_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalGroupBox_8)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setMargin(9)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.button_wep_start_hirte_ap = QtGui.QPushButton(self.verticalGroupBox_8)
        self.button_wep_start_hirte_ap.setObjectName(_fromUtf8("button_wep_start_hirte_ap"))
        self.verticalLayout_8.addWidget(self.button_wep_start_hirte_ap)
        self.vboxlayout1.addWidget(self.verticalGroupBox_8)
        self.groupBox_4 = QtGui.QGroupBox(self.page1)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.button_wep_start_hirte_adhoc = QtGui.QPushButton(self.groupBox_4)
        self.button_wep_start_hirte_adhoc.setObjectName(_fromUtf8("button_wep_start_hirte_adhoc"))
        self.verticalLayout_12.addWidget(self.button_wep_start_hirte_adhoc)
        self.vboxlayout1.addWidget(self.groupBox_4)
        spacerItem7 = QtGui.QSpacerItem(41, 111, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem7)
        self.toolBox2_2.addItem(self.page1, _fromUtf8(""))
        self.gridlayout5.addWidget(self.toolBox2_2, 1, 0, 1, 1)
        self.textLabel4_4_3 = QtGui.QLabel(self.TabPage1)
        self.textLabel4_4_3.setWordWrap(False)
        self.textLabel4_4_3.setObjectName(_fromUtf8("textLabel4_4_3"))
        self.gridlayout5.addWidget(self.textLabel4_4_3, 0, 0, 1, 1)
        self.tabWidget2.addTab(self.TabPage1, _fromUtf8(""))
        self.TabPage2 = QtGui.QWidget()
        self.TabPage2.setObjectName(_fromUtf8("TabPage2"))
        self.gridlayout7 = QtGui.QGridLayout(self.TabPage2)
        self.gridlayout7.setObjectName(_fromUtf8("gridlayout7"))
        self.textLabel4_4_2_3 = QtGui.QLabel(self.TabPage2)
        self.textLabel4_4_2_3.setWordWrap(False)
        self.textLabel4_4_2_3.setObjectName(_fromUtf8("textLabel4_4_2_3"))
        self.gridlayout7.addWidget(self.textLabel4_4_2_3, 0, 0, 1, 1)
        self.toolBox4_2 = QtGui.QToolBox(self.TabPage2)
        self.toolBox4_2.setObjectName(_fromUtf8("toolBox4_2"))
        self.page21 = QtGui.QWidget()
        self.page21.setGeometry(QtCore.QRect(0, 0, 192, 142))
        self.page21.setObjectName(_fromUtf8("page21"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.page21)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.groupBox = QtGui.QGroupBox(self.page21)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.button_wpa_start_sniff = QtGui.QPushButton(self.groupBox)
        self.button_wpa_start_sniff.setObjectName(_fromUtf8("button_wpa_start_sniff"))
        self.verticalLayout_10.addWidget(self.button_wpa_start_sniff)
        self.vboxlayout2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page21)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.button_wpa_test_inj = QtGui.QPushButton(self.groupBox_2)
        self.button_wpa_test_inj.setObjectName(_fromUtf8("button_wpa_test_inj"))
        self.verticalLayout_9.addWidget(self.button_wpa_test_inj)
        self.vboxlayout2.addWidget(self.groupBox_2)
        spacerItem8 = QtGui.QSpacerItem(41, 140, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout2.addItem(spacerItem8)
        self.toolBox4_2.addItem(self.page21, _fromUtf8(""))
        self.page2 = QtGui.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 373, 218))
        self.page2.setObjectName(_fromUtf8("page2"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.page2)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.groupBox4_2 = QtGui.QGroupBox(self.page2)
        self.groupBox4_2.setObjectName(_fromUtf8("groupBox4_2"))
        self.vboxlayout4 = QtGui.QVBoxLayout(self.groupBox4_2)
        self.vboxlayout4.setObjectName(_fromUtf8("vboxlayout4"))
        self.textLabel8_2 = QtGui.QLabel(self.groupBox4_2)
        self.textLabel8_2.setWordWrap(False)
        self.textLabel8_2.setObjectName(_fromUtf8("textLabel8_2"))
        self.vboxlayout4.addWidget(self.textLabel8_2)
        self.combo_wpa_mac_hand = QtGui.QComboBox(self.groupBox4_2)
        self.combo_wpa_mac_hand.setEditable(True)
        self.combo_wpa_mac_hand.setObjectName(_fromUtf8("combo_wpa_mac_hand"))
        self.vboxlayout4.addWidget(self.combo_wpa_mac_hand)
        self.button_wpa_autoload_clients = QtGui.QPushButton(self.groupBox4_2)
        self.button_wpa_autoload_clients.setObjectName(_fromUtf8("button_wpa_autoload_clients"))
        self.vboxlayout4.addWidget(self.button_wpa_autoload_clients)
        self.textLabel8_2_2 = QtGui.QLabel(self.groupBox4_2)
        self.textLabel8_2_2.setWordWrap(False)
        self.textLabel8_2_2.setObjectName(_fromUtf8("textLabel8_2_2"))
        self.vboxlayout4.addWidget(self.textLabel8_2_2)
        self.spin_wpa_deauth_hand = QtGui.QSpinBox(self.groupBox4_2)
        self.spin_wpa_deauth_hand.setProperty("value", 4)
        self.spin_wpa_deauth_hand.setObjectName(_fromUtf8("spin_wpa_deauth_hand"))
        self.vboxlayout4.addWidget(self.spin_wpa_deauth_hand)
        self.textLabel9_2 = QtGui.QLabel(self.groupBox4_2)
        self.textLabel9_2.setWordWrap(False)
        self.textLabel9_2.setObjectName(_fromUtf8("textLabel9_2"))
        self.vboxlayout4.addWidget(self.textLabel9_2)
        self.button_wpa_deauth_hand = QtGui.QPushButton(self.groupBox4_2)
        self.button_wpa_deauth_hand.setObjectName(_fromUtf8("button_wpa_deauth_hand"))
        self.vboxlayout4.addWidget(self.button_wpa_deauth_hand)
        self.vboxlayout3.addWidget(self.groupBox4_2)
        spacerItem9 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem9)
        self.toolBox4_2.addItem(self.page2, _fromUtf8(""))
        self.gridlayout7.addWidget(self.toolBox4_2, 1, 0, 1, 1)
        self.tabWidget2.addTab(self.TabPage2, _fromUtf8(""))
        self.TabPage3 = QtGui.QWidget()
        self.TabPage3.setObjectName(_fromUtf8("TabPage3"))
        self.gridlayout8 = QtGui.QGridLayout(self.TabPage3)
        self.gridlayout8.setObjectName(_fromUtf8("gridlayout8"))
        self.textLabel4_4_2_3_2 = QtGui.QLabel(self.TabPage3)
        self.textLabel4_4_2_3_2.setWordWrap(False)
        self.textLabel4_4_2_3_2.setObjectName(_fromUtf8("textLabel4_4_2_3_2"))
        self.gridlayout8.addWidget(self.textLabel4_4_2_3_2, 0, 0, 1, 1)
        self.toolBox5 = QtGui.QToolBox(self.TabPage3)
        self.toolBox5.setObjectName(_fromUtf8("toolBox5"))
        self.page12 = QtGui.QWidget()
        self.page12.setGeometry(QtCore.QRect(0, 0, 606, 379))
        self.page12.setObjectName(_fromUtf8("page12"))
        self.vboxlayout5 = QtGui.QVBoxLayout(self.page12)
        self.vboxlayout5.setObjectName(_fromUtf8("vboxlayout5"))
        self.textLabel2_3 = QtGui.QLabel(self.page12)
        self.textLabel2_3.setWordWrap(False)
        self.textLabel2_3.setObjectName(_fromUtf8("textLabel2_3"))
        self.vboxlayout5.addWidget(self.textLabel2_3)
        self.line_fake_ap_essid = QtGui.QLineEdit(self.page12)
        self.line_fake_ap_essid.setObjectName(_fromUtf8("line_fake_ap_essid"))
        self.vboxlayout5.addWidget(self.line_fake_ap_essid)
        self.textLabel2_3_3 = QtGui.QLabel(self.page12)
        self.textLabel2_3_3.setWordWrap(False)
        self.textLabel2_3_3.setObjectName(_fromUtf8("textLabel2_3_3"))
        self.vboxlayout5.addWidget(self.textLabel2_3_3)
        self.line_fake_ap_chan = QtGui.QLineEdit(self.page12)
        self.line_fake_ap_chan.setObjectName(_fromUtf8("line_fake_ap_chan"))
        self.vboxlayout5.addWidget(self.line_fake_ap_chan)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.groupBox14 = QtGui.QGroupBox(self.page12)
        self.groupBox14.setObjectName(_fromUtf8("groupBox14"))
        self.hboxlayout3 = QtGui.QHBoxLayout(self.groupBox14)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.check_fake_ap_wep = QtGui.QCheckBox(self.groupBox14)
        self.check_fake_ap_wep.setObjectName(_fromUtf8("check_fake_ap_wep"))
        self.hboxlayout3.addWidget(self.check_fake_ap_wep)
        self.radioButton13 = QtGui.QRadioButton(self.groupBox14)
        self.radioButton13.setChecked(True)
        self.radioButton13.setObjectName(_fromUtf8("radioButton13"))
        self.hboxlayout3.addWidget(self.radioButton13)
        self.radio_fake_ap_wpa = QtGui.QRadioButton(self.groupBox14)
        self.radio_fake_ap_wpa.setObjectName(_fromUtf8("radio_fake_ap_wpa"))
        self.hboxlayout3.addWidget(self.radio_fake_ap_wpa)
        self.radio_fake_ap_wpa2 = QtGui.QRadioButton(self.groupBox14)
        self.radio_fake_ap_wpa2.setObjectName(_fromUtf8("radio_fake_ap_wpa2"))
        self.hboxlayout3.addWidget(self.radio_fake_ap_wpa2)
        self.hboxlayout2.addWidget(self.groupBox14)
        self.vboxlayout6 = QtGui.QVBoxLayout()
        self.vboxlayout6.setObjectName(_fromUtf8("vboxlayout6"))
        self.textLabel3 = QtGui.QLabel(self.page12)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName(_fromUtf8("textLabel3"))
        self.vboxlayout6.addWidget(self.textLabel3)
        self.line_fake_ap_wep_key = QtGui.QLineEdit(self.page12)
        self.line_fake_ap_wep_key.setObjectName(_fromUtf8("line_fake_ap_wep_key"))
        self.vboxlayout6.addWidget(self.line_fake_ap_wep_key)
        self.hboxlayout2.addLayout(self.vboxlayout6)
        self.vboxlayout5.addLayout(self.hboxlayout2)
        self.groupBox13 = QtGui.QGroupBox(self.page12)
        self.groupBox13.setObjectName(_fromUtf8("groupBox13"))
        self.hboxlayout4 = QtGui.QHBoxLayout(self.groupBox13)
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.radio_fake_ap_wep40 = QtGui.QRadioButton(self.groupBox13)
        self.radio_fake_ap_wep40.setChecked(True)
        self.radio_fake_ap_wep40.setObjectName(_fromUtf8("radio_fake_ap_wep40"))
        self.hboxlayout4.addWidget(self.radio_fake_ap_wep40)
        self.radio_fake_ap_tkip = QtGui.QRadioButton(self.groupBox13)
        self.radio_fake_ap_tkip.setObjectName(_fromUtf8("radio_fake_ap_tkip"))
        self.hboxlayout4.addWidget(self.radio_fake_ap_tkip)
        self.radio_fake_ap_wrap = QtGui.QRadioButton(self.groupBox13)
        self.radio_fake_ap_wrap.setObjectName(_fromUtf8("radio_fake_ap_wrap"))
        self.hboxlayout4.addWidget(self.radio_fake_ap_wrap)
        self.radio_fake_ap_ccmp = QtGui.QRadioButton(self.groupBox13)
        self.radio_fake_ap_ccmp.setObjectName(_fromUtf8("radio_fake_ap_ccmp"))
        self.hboxlayout4.addWidget(self.radio_fake_ap_ccmp)
        self.radio_fake_ap_wep104 = QtGui.QRadioButton(self.groupBox13)
        self.radio_fake_ap_wep104.setObjectName(_fromUtf8("radio_fake_ap_wep104"))
        self.hboxlayout4.addWidget(self.radio_fake_ap_wep104)
        self.vboxlayout5.addWidget(self.groupBox13)
        self.groupBox7 = QtGui.QGroupBox(self.page12)
        self.groupBox7.setObjectName(_fromUtf8("groupBox7"))
        self.gridlayout9 = QtGui.QGridLayout(self.groupBox7)
        self.gridlayout9.setObjectName(_fromUtf8("gridlayout9"))
        self.check_fake_ap_adhoc_mode = QtGui.QCheckBox(self.groupBox7)
        self.check_fake_ap_adhoc_mode.setObjectName(_fromUtf8("check_fake_ap_adhoc_mode"))
        self.gridlayout9.addWidget(self.check_fake_ap_adhoc_mode, 0, 0, 1, 1)
        self.check_fake_ap_hidden_ssid = QtGui.QCheckBox(self.groupBox7)
        self.check_fake_ap_hidden_ssid.setObjectName(_fromUtf8("check_fake_ap_hidden_ssid"))
        self.gridlayout9.addWidget(self.check_fake_ap_hidden_ssid, 0, 1, 1, 1)
        self.check_fake_ap_no_broadcast = QtGui.QCheckBox(self.groupBox7)
        self.check_fake_ap_no_broadcast.setObjectName(_fromUtf8("check_fake_ap_no_broadcast"))
        self.gridlayout9.addWidget(self.check_fake_ap_no_broadcast, 0, 2, 1, 1)
        self.check_fake_ap_all_probes = QtGui.QCheckBox(self.groupBox7)
        self.check_fake_ap_all_probes.setObjectName(_fromUtf8("check_fake_ap_all_probes"))
        self.gridlayout9.addWidget(self.check_fake_ap_all_probes, 0, 3, 1, 1)
        self.vboxlayout5.addWidget(self.groupBox7)
        self.button_fake_ap_start = QtGui.QPushButton(self.page12)
        self.button_fake_ap_start.setObjectName(_fromUtf8("button_fake_ap_start"))
        self.vboxlayout5.addWidget(self.button_fake_ap_start)
        spacerItem10 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout5.addItem(spacerItem10)
        self.toolBox5.addItem(self.page12, _fromUtf8(""))
        self.gridlayout8.addWidget(self.toolBox5, 1, 0, 1, 1)
        self.tabWidget2.addTab(self.TabPage3, _fromUtf8(""))
        self.TabPage4 = QtGui.QWidget()
        self.TabPage4.setObjectName(_fromUtf8("TabPage4"))
        self.gridlayout10 = QtGui.QGridLayout(self.TabPage4)
        self.gridlayout10.setObjectName(_fromUtf8("gridlayout10"))
        self.toolBox5_3 = QtGui.QToolBox(self.TabPage4)
        self.toolBox5_3.setObjectName(_fromUtf8("toolBox5_3"))
        self.page13 = QtGui.QWidget()
        self.page13.setGeometry(QtCore.QRect(0, 0, 423, 99))
        self.page13.setObjectName(_fromUtf8("page13"))
        self.vboxlayout7 = QtGui.QVBoxLayout(self.page13)
        self.vboxlayout7.setObjectName(_fromUtf8("vboxlayout7"))
        self.groupBox1_5 = QtGui.QGroupBox(self.page13)
        self.groupBox1_5.setObjectName(_fromUtf8("groupBox1_5"))
        self.vboxlayout8 = QtGui.QVBoxLayout(self.groupBox1_5)
        self.vboxlayout8.setObjectName(_fromUtf8("vboxlayout8"))
        self.textLabel10_4 = QtGui.QLabel(self.groupBox1_5)
        self.textLabel10_4.setWordWrap(False)
        self.textLabel10_4.setObjectName(_fromUtf8("textLabel10_4"))
        self.vboxlayout8.addWidget(self.textLabel10_4)
        self.button_crack_wep_aircrack = QtGui.QPushButton(self.groupBox1_5)
        self.button_crack_wep_aircrack.setObjectName(_fromUtf8("button_crack_wep_aircrack"))
        self.vboxlayout8.addWidget(self.button_crack_wep_aircrack)
        self.vboxlayout7.addWidget(self.groupBox1_5)
        spacerItem11 = QtGui.QSpacerItem(31, 91, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout7.addItem(spacerItem11)
        self.toolBox5_3.addItem(self.page13, _fromUtf8(""))
        self.page22 = QtGui.QWidget()
        self.page22.setGeometry(QtCore.QRect(0, 0, 247, 251))
        self.page22.setObjectName(_fromUtf8("page22"))
        self.gridlayout11 = QtGui.QGridLayout(self.page22)
        self.gridlayout11.setObjectName(_fromUtf8("gridlayout11"))
        self.groupBox1_2_3 = QtGui.QGroupBox(self.page22)
        self.groupBox1_2_3.setObjectName(_fromUtf8("groupBox1_2_3"))
        self.vboxlayout9 = QtGui.QVBoxLayout(self.groupBox1_2_3)
        self.vboxlayout9.setObjectName(_fromUtf8("vboxlayout9"))
        self.textLabel11_2_4 = QtGui.QLabel(self.groupBox1_2_3)
        self.textLabel11_2_4.setWordWrap(False)
        self.textLabel11_2_4.setObjectName(_fromUtf8("textLabel11_2_4"))
        self.vboxlayout9.addWidget(self.textLabel11_2_4)
        self.line_crack_wpa_dictionary = QtGui.QLineEdit(self.groupBox1_2_3)
        self.line_crack_wpa_dictionary.setObjectName(_fromUtf8("line_crack_wpa_dictionary"))
        self.vboxlayout9.addWidget(self.line_crack_wpa_dictionary)
        self.button_crack_wpa_aircrack = QtGui.QPushButton(self.groupBox1_2_3)
        self.button_crack_wpa_aircrack.setObjectName(_fromUtf8("button_crack_wpa_aircrack"))
        self.vboxlayout9.addWidget(self.button_crack_wpa_aircrack)
        self.gridlayout11.addWidget(self.groupBox1_2_3, 0, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(31, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout11.addItem(spacerItem12, 2, 0, 1, 1)
        self.groupBox1_3_3 = QtGui.QGroupBox(self.page22)
        self.groupBox1_3_3.setObjectName(_fromUtf8("groupBox1_3_3"))
        self.vboxlayout10 = QtGui.QVBoxLayout(self.groupBox1_3_3)
        self.vboxlayout10.setObjectName(_fromUtf8("vboxlayout10"))
        self.textLabel10_2_3 = QtGui.QLabel(self.groupBox1_3_3)
        self.textLabel10_2_3.setWordWrap(False)
        self.textLabel10_2_3.setObjectName(_fromUtf8("textLabel10_2_3"))
        self.vboxlayout10.addWidget(self.textLabel10_2_3)
        self.textLabel11_2_2_3 = QtGui.QLabel(self.groupBox1_3_3)
        self.textLabel11_2_2_3.setWordWrap(False)
        self.textLabel11_2_2_3.setObjectName(_fromUtf8("textLabel11_2_2_3"))
        self.vboxlayout10.addWidget(self.textLabel11_2_2_3)
        self.line_crack_wpa_dictionary_pyrit = QtGui.QLineEdit(self.groupBox1_3_3)
        self.line_crack_wpa_dictionary_pyrit.setObjectName(_fromUtf8("line_crack_wpa_dictionary_pyrit"))
        self.vboxlayout10.addWidget(self.line_crack_wpa_dictionary_pyrit)
        self.button_crack_wpa_pyrit = QtGui.QPushButton(self.groupBox1_3_3)
        self.button_crack_wpa_pyrit.setObjectName(_fromUtf8("button_crack_wpa_pyrit"))
        self.vboxlayout10.addWidget(self.button_crack_wpa_pyrit)
        self.gridlayout11.addWidget(self.groupBox1_3_3, 1, 0, 1, 1)
        self.toolBox5_3.addItem(self.page22, _fromUtf8(""))
        self.page3 = QtGui.QWidget()
        self.page3.setGeometry(QtCore.QRect(0, 0, 400, 144))
        self.page3.setObjectName(_fromUtf8("page3"))
        self.gridlayout12 = QtGui.QGridLayout(self.page3)
        self.gridlayout12.setObjectName(_fromUtf8("gridlayout12"))
        self.groupBox1_3_3_2 = QtGui.QGroupBox(self.page3)
        self.groupBox1_3_3_2.setObjectName(_fromUtf8("groupBox1_3_3_2"))
        self.vboxlayout11 = QtGui.QVBoxLayout(self.groupBox1_3_3_2)
        self.vboxlayout11.setObjectName(_fromUtf8("vboxlayout11"))
        self.textLabel10_2_3_2 = QtGui.QLabel(self.groupBox1_3_3_2)
        self.textLabel10_2_3_2.setWordWrap(False)
        self.textLabel10_2_3_2.setObjectName(_fromUtf8("textLabel10_2_3_2"))
        self.vboxlayout11.addWidget(self.textLabel10_2_3_2)
        self.textLabel11_2_2_3_2 = QtGui.QLabel(self.groupBox1_3_3_2)
        self.textLabel11_2_2_3_2.setWordWrap(False)
        self.textLabel11_2_2_3_2.setObjectName(_fromUtf8("textLabel11_2_2_3_2"))
        self.vboxlayout11.addWidget(self.textLabel11_2_2_3_2)
        self.line_crack_wpa_rainbow_tables_file = QtGui.QLineEdit(self.groupBox1_3_3_2)
        self.line_crack_wpa_rainbow_tables_file.setObjectName(_fromUtf8("line_crack_wpa_rainbow_tables_file"))
        self.vboxlayout11.addWidget(self.line_crack_wpa_rainbow_tables_file)
        self.button_crack_wpa_rainbow_tables = QtGui.QPushButton(self.groupBox1_3_3_2)
        self.button_crack_wpa_rainbow_tables.setObjectName(_fromUtf8("button_crack_wpa_rainbow_tables"))
        self.vboxlayout11.addWidget(self.button_crack_wpa_rainbow_tables)
        self.gridlayout12.addWidget(self.groupBox1_3_3_2, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(31, 101, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout12.addItem(spacerItem13, 1, 0, 1, 1)
        self.toolBox5_3.addItem(self.page3, _fromUtf8(""))
        self.gridlayout10.addWidget(self.toolBox5_3, 1, 0, 1, 1)
        self.textLabel4_4_2_2_3 = QtGui.QLabel(self.TabPage4)
        self.textLabel4_4_2_2_3.setWordWrap(False)
        self.textLabel4_4_2_2_3.setObjectName(_fromUtf8("textLabel4_4_2_2_3"))
        self.gridlayout10.addWidget(self.textLabel4_4_2_2_3, 0, 0, 1, 1)
        self.tabWidget2.addTab(self.TabPage4, _fromUtf8(""))
        self.TabPage5 = QtGui.QWidget()
        self.TabPage5.setObjectName(_fromUtf8("TabPage5"))
        self.gridlayout13 = QtGui.QGridLayout(self.TabPage5)
        self.gridlayout13.setObjectName(_fromUtf8("gridlayout13"))
        self.textLabel4 = QtGui.QLabel(self.TabPage5)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName(_fromUtf8("textLabel4"))
        self.gridlayout13.addWidget(self.textLabel4, 0, 0, 1, 1)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName(_fromUtf8("hboxlayout5"))
        self.button_database_add = QtGui.QPushButton(self.TabPage5)
        self.button_database_add.setObjectName(_fromUtf8("button_database_add"))
        self.hboxlayout5.addWidget(self.button_database_add)
        self.button_database_delete = QtGui.QPushButton(self.TabPage5)
        self.button_database_delete.setObjectName(_fromUtf8("button_database_delete"))
        self.hboxlayout5.addWidget(self.button_database_delete)
        self.line_database = QtGui.QLineEdit(self.TabPage5)
        self.line_database.setObjectName(_fromUtf8("line_database"))
        self.hboxlayout5.addWidget(self.line_database)
        self.button_database_reload = QtGui.QPushButton(self.TabPage5)
        self.button_database_reload.setObjectName(_fromUtf8("button_database_reload"))
        self.hboxlayout5.addWidget(self.button_database_reload)
        self.button_database_save = QtGui.QPushButton(self.TabPage5)
        self.button_database_save.setObjectName(_fromUtf8("button_database_save"))
        self.hboxlayout5.addWidget(self.button_database_save)
        self.gridlayout13.addLayout(self.hboxlayout5, 2, 0, 1, 1)
        self.table_database = QtGui.QTableWidget(self.TabPage5)
        self.table_database.setRowCount(1)
        self.table_database.setColumnCount(5)
        self.table_database.setObjectName(_fromUtf8("table_database"))
        item = QtGui.QTableWidgetItem()
        self.table_database.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_database.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_database.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_database.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_database.setHorizontalHeaderItem(4, item)
        self.table_database.verticalHeader().setDefaultSectionSize(23)
        self.gridlayout13.addWidget(self.table_database, 1, 0, 1, 1)
        self.tabWidget2.addTab(self.TabPage5, _fromUtf8(""))
        self.TabPage6 = QtGui.QWidget()
        self.TabPage6.setObjectName(_fromUtf8("TabPage6"))
        self.vboxlayout12 = QtGui.QVBoxLayout(self.TabPage6)
        self.vboxlayout12.setObjectName(_fromUtf8("vboxlayout12"))
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setMargin(8)
        self.hboxlayout6.setObjectName(_fromUtf8("hboxlayout6"))
        spacerItem14 = QtGui.QSpacerItem(51, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem14)
        self.textLabel14 = QtGui.QLabel(self.TabPage6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textLabel14.setFont(font)
        self.textLabel14.setWordWrap(False)
        self.textLabel14.setObjectName(_fromUtf8("textLabel14"))
        self.hboxlayout6.addWidget(self.textLabel14)
        spacerItem15 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem15)
        self.vboxlayout12.addLayout(self.hboxlayout6)
        self.textLabel16 = QtGui.QLabel(self.TabPage6)
        self.textLabel16.setWordWrap(False)
        self.textLabel16.setObjectName(_fromUtf8("textLabel16"))
        self.vboxlayout12.addWidget(self.textLabel16)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setMargin(8)
        self.hboxlayout7.setObjectName(_fromUtf8("hboxlayout7"))
        spacerItem16 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem16)
        self.vboxlayout12.addLayout(self.hboxlayout7)
        self.textLabel17_2 = QtGui.QLabel(self.TabPage6)
        self.textLabel17_2.setWordWrap(False)
        self.textLabel17_2.setObjectName(_fromUtf8("textLabel17_2"))
        self.vboxlayout12.addWidget(self.textLabel17_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(8)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.vboxlayout12.addLayout(self.horizontalLayout)
        self.label = QtGui.QLabel(self.TabPage6)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout12.addWidget(self.label)
        spacerItem18 = QtGui.QSpacerItem(41, 140, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout12.addItem(spacerItem18)
        self.tabWidget2.addTab(self.TabPage6, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget2, 0, 0, 1, 3)
        Main_window.setCentralWidget(self.widget)

        self.retranslateUi(Main_window)
        self.tabWidget2.setCurrentIndex(4)
        self.toolBox3_2.setCurrentIndex(0)
        self.toolBox2_2.setCurrentIndex(2)
        self.toolBox4_2.setCurrentIndex(0)
        self.toolBox5.setCurrentIndex(0)
        self.toolBox5_3.setCurrentIndex(2)
        QtCore.QObject.connect(self.button_crack_wep_aircrack, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_crack_wep_aircrack)
        QtCore.QObject.connect(self.button_crack_wpa_aircrack, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_crack_wpa_aircrack)
        QtCore.QObject.connect(self.button_crack_wpa_pyrit, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_crack_wpa_pyrit)
        QtCore.QObject.connect(self.button_crack_wpa_rainbow_tables, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_crack_wpa_rainbow_tables)
        QtCore.QObject.connect(self.button_fake_ap_start, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_fake_ap_start)
        QtCore.QObject.connect(self.button_gath_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_gath_clean)
        QtCore.QObject.connect(self.button_reload_interfaces, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_reload_interfaces)
        QtCore.QObject.connect(self.button_rescan_networks, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_rescan_networks)
        QtCore.QObject.connect(self.button_wep_start_latte, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_wep_start_latte)
        QtCore.QObject.connect(self.button_wep_test_inj, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_test_inj)
        QtCore.QObject.connect(self.button_wpa_autoload_clients, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_autoload_victim_clients)
        QtCore.QObject.connect(self.button_wpa_deauth_hand, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_wpa_deauth_hand)
        QtCore.QObject.connect(self.button_wpa_start_sniff, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_start_sniffing)
        QtCore.QObject.connect(self.button_wpa_test_inj, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_test_inj)
        QtCore.QObject.connect(self.combo_wpa_mac_hand, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Main_window.slot_line_wpa_mac_hand)
        QtCore.QObject.connect(self.line_crack_wpa_dictionary, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Main_window.slot_line_crack_wpa_dictionary)
        QtCore.QObject.connect(self.line_crack_wpa_dictionary_pyrit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Main_window.slot_line_crack_wpa_dictionary_pyrit)
        QtCore.QObject.connect(self.line_crack_wpa_rainbow_tables_file, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Main_window.slot_line_crack_wpa_rainbow_tables_file)
        QtCore.QObject.connect(self.line_gath_logs, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Main_window.slot_line_gath_logs)
        QtCore.QObject.connect(self.spin_wpa_deauth_hand, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Main_window.slot_line_wpa_deauth_hand)
        QtCore.QObject.connect(self.button_random_mac, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_random_mac)
        QtCore.QObject.connect(self.line_database, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Main_window.slot_line_database)
        QtCore.QObject.connect(self.button_database_delete, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_database_delete)
        QtCore.QObject.connect(self.button_database_reload, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_database_reload)
        QtCore.QObject.connect(self.button_database_save, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_database_save)
        QtCore.QObject.connect(self.button_database_add, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_database_add)
        QtCore.QObject.connect(self.button_monitor, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_monitor)
        QtCore.QObject.connect(self.button_wep_start_sniff, QtCore.SIGNAL(_fromUtf8("clicked()")), Main_window.slot_start_sniffing)
        QtCore.QMetaObject.connectSlotsByName(Main_window)

    def retranslateUi(self, Main_window):
        Main_window.setWindowTitle(_translate("Main_window", "Gerix wifi cracker", None))
        self.textLabel1.setText(_translate("Main_window", "Hello and Welcome!<br>\n"
"Gerix Wifi Cracker is a GUI that can help you to work in Wireless 802.11 Penetration Test.<br>\n"
"Created by Emanuele `emgent` Gentili and Emanuele `crossbower` Acri from Gerix.IT company. The tool is under GPL 2 License.\n"
"<br> enJoy! <br>", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab), _translate("Main_window", "Welcome", None))
        self.button_reload_interfaces.setText(_translate("Main_window", "Reload wireless interfaces", None))
        self.button_random_mac.setText(_translate("Main_window", "Set random MAC address", None))
        self.button_monitor.setText(_translate("Main_window", "Enable/Disable Monitor Mode", None))
        self.textLabel1_2.setText(_translate("Main_window", "Channel:", None))
        self.combo_channel.setItemText(0, _translate("Main_window", "all channels", None))
        self.combo_channel.setItemText(1, _translate("Main_window", "1", None))
        self.combo_channel.setItemText(2, _translate("Main_window", "2", None))
        self.combo_channel.setItemText(3, _translate("Main_window", "3", None))
        self.combo_channel.setItemText(4, _translate("Main_window", "4", None))
        self.combo_channel.setItemText(5, _translate("Main_window", "5", None))
        self.combo_channel.setItemText(6, _translate("Main_window", "6", None))
        self.combo_channel.setItemText(7, _translate("Main_window", "7", None))
        self.combo_channel.setItemText(8, _translate("Main_window", "8", None))
        self.combo_channel.setItemText(9, _translate("Main_window", "9", None))
        self.combo_channel.setItemText(10, _translate("Main_window", "10", None))
        self.combo_channel.setItemText(11, _translate("Main_window", "11", None))
        self.combo_channel.setItemText(12, _translate("Main_window", "12", None))
        self.combo_channel.setItemText(13, _translate("Main_window", "13", None))
        self.textLabel2_4.setText(_translate("Main_window", "Seconds:", None))
        self.button_rescan_networks.setText(_translate("Main_window", "Rescan networks", None))
        self.textLabel3_5_6_2_2.setText(_translate("Main_window", "Select the <b>interface</b>:", None))
        self.textLabel3_4_4.setText(_translate("Main_window", "Directory for session files (logs, .cap, ...):", None))
        self.button_gath_clean.setText(_translate("Main_window", "Clean old session files", None))
        self.textLabel3_5_6_2.setText(_translate("Main_window", "Select the <b>target network</b>:", None))
        item = self.table_interfaces.horizontalHeaderItem(0)
        item.setText(_translate("Main_window", "Interface", None))
        item = self.table_interfaces.horizontalHeaderItem(1)
        item.setText(_translate("Main_window", "MAC", None))
        item = self.table_interfaces.horizontalHeaderItem(2)
        item.setText(_translate("Main_window", "Chipset", None))
        item = self.table_interfaces.horizontalHeaderItem(3)
        item.setText(_translate("Main_window", "Driver", None))
        item = self.table_interfaces.horizontalHeaderItem(4)
        item.setText(_translate("Main_window", "Mode", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Main_window", "Essid", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Main_window", "Bssid", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Main_window", "Channel", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Main_window", "Signal", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Main_window", "Enc", None))
        self.toolBox3_2.setItemText(self.toolBox3_2.indexOf(self.page1), _translate("Main_window", "General configurations and network selection.", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.TabPage), _translate("Main_window", "Configuration", None))
        self.button_wep_start_sniff.setText(_translate("Main_window", "Start Sniffing and Logging", None))
        self.button_wep_test_inj.setText(_translate("Main_window", "Performs a test of injection AP", None))
        self.toolBox2_2.setItemText(self.toolBox2_2.indexOf(self.page11), _translate("Main_window", "General functionalities", None))
        self.verticalGroupBox_3.setTitle(_translate("Main_window", "ChopChop attack", None))
        self.button_wep_fake_auth_chop.setText(_translate("Main_window", "Start false access point Authentication on victim", None))
        self.button_wep_start_chop.setText(_translate("Main_window", "Start the ChopChop attack", None))
        self.button_wep_create_arp_chop.setText(_translate("Main_window", "Create the ARP packet to be injected on the victim access point", None))
        self.button_wep_arp_inj_chop.setText(_translate("Main_window", "Inject the created packet on victim access point", None))
        self.verticalGroupBox_4.setTitle(_translate("Main_window", "Fragmentation attack", None))
        self.button_wep_assoc_fake_auth_frag.setText(_translate("Main_window", "Associate with AP using fake auth", None))
        self.button_wep_start_frag.setText(_translate("Main_window", "Fragmentation attack", None))
        self.button_wep_create_arp_frag.setText(_translate("Main_window", "Create the ARP packet to be injected on the victim access point", None))
        self.button_wep_arp_inj_frag.setText(_translate("Main_window", "Inject the created packet on victim access point", None))
        self.toolBox2_2.setItemText(self.toolBox2_2.indexOf(self.page2), _translate("Main_window", "WEP Attacks (no-client)", None))
        self.verticalGroupBox_5.setTitle(_translate("Main_window", "ARP request replay attack", None))
        self.button_wep_assoc_fake_auth_rep.setText(_translate("Main_window", "Associate with AP using fake auth", None))
        self.button_wep_start_rep.setText(_translate("Main_window", "ARP request replay", None))
        self.verticalGroupBox_6.setTitle(_translate("Main_window", "ARP request attack", None))
        self.button_wep_assoc_fake_auth_req.setText(_translate("Main_window", "Associate with AP using fake auth", None))
        self.textLabel7_2.setText(_translate("Main_window", "Maximum packet length:", None))
        self.textLabel6_3.setText(_translate("Main_window", "Minimum packet length:", None))
        self.button_wep_capture_req.setText(_translate("Main_window", "Capture replay packets", None))
        self.verticalGroupBox_7.setTitle(_translate("Main_window", "Fragmentation client attack", None))
        self.textLabel6_2_2.setText(_translate("Main_window", "Add victim client MAC:", None))
        self.button_wep_autoload_clients_cfrag.setText(_translate("Main_window", "Autoload victim clients", None))
        self.button_wep_arp_inj_cfrag.setText(_translate("Main_window", "Start Client Fragmentation Attack", None))
        self.toolBox2_2.setItemText(self.toolBox2_2.indexOf(self.page), _translate("Main_window", "WEP Attacks (with clients)", None))
        self.groupBox_3.setTitle(_translate("Main_window", "Caffe-Latte attack in access point mode", None))
        self.button_wep_start_latte.setText(_translate("Main_window", "Start Caffe-Latte attack", None))
        self.verticalGroupBox_8.setTitle(_translate("Main_window", "Hirte attack in access point mode", None))
        self.button_wep_start_hirte_ap.setText(_translate("Main_window", "Start Hirte attack", None))
        self.groupBox_4.setTitle(_translate("Main_window", "Hirte attack in ad-hoc mode", None))
        self.button_wep_start_hirte_adhoc.setText(_translate("Main_window", "Start Hirte attack", None))
        self.toolBox2_2.setItemText(self.toolBox2_2.indexOf(self.page1), _translate("Main_window", "WEP Attack (with clients, in Access Point and Ad-Hoc mode)", None))
        self.textLabel4_4_3.setText(_translate("Main_window", "<h2>Welcome in WEP Attacks Control Panel</h2>", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.TabPage1), _translate("Main_window", "WEP", None))
        self.textLabel4_4_2_3.setText(_translate("Main_window", "<h2>Welcome in WPA Attacks Control Panel</h2>", None))
        self.groupBox.setTitle(_translate("Main_window", "Functionalities", None))
        self.button_wpa_start_sniff.setText(_translate("Main_window", "Start Sniffing and Logging", None))
        self.groupBox_2.setTitle(_translate("Main_window", "Tests", None))
        self.button_wpa_test_inj.setText(_translate("Main_window", "Performs a test of injection AP", None))
        self.toolBox4_2.setItemText(self.toolBox4_2.indexOf(self.page21), _translate("Main_window", "General functionalities", None))
        self.groupBox4_2.setTitle(_translate("Main_window", "WPA handshake attack", None))
        self.textLabel8_2.setText(_translate("Main_window", "Add victim client MAC:", None))
        self.button_wpa_autoload_clients.setText(_translate("Main_window", "Autoload victim clients", None))
        self.textLabel8_2_2.setText(_translate("Main_window", "Add the deauth number:", None))
        self.textLabel9_2.setText(_translate("Main_window", "Now you need to capture the HandShake, start the deauthentication.", None))
        self.button_wpa_deauth_hand.setText(_translate("Main_window", "Client deauthentication", None))
        self.toolBox4_2.setItemText(self.toolBox4_2.indexOf(self.page2), _translate("Main_window", "WPA attacks", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.TabPage2), _translate("Main_window", "WPA", None))
        self.textLabel4_4_2_3_2.setText(_translate("Main_window", "<h2>Welcome in Fake Access Point Control Panel</h2>", None))
        self.textLabel2_3.setText(_translate("Main_window", "Access point ESSID:", None))
        self.line_fake_ap_essid.setText(_translate("Main_window", "honeypot", None))
        self.textLabel2_3_3.setText(_translate("Main_window", "Access point channel:", None))
        self.line_fake_ap_chan.setText(_translate("Main_window", "12", None))
        self.groupBox14.setTitle(_translate("Main_window", "Cryptography tags", None))
        self.check_fake_ap_wep.setText(_translate("Main_window", "WEP", None))
        self.radioButton13.setText(_translate("Main_window", "None", None))
        self.radio_fake_ap_wpa.setText(_translate("Main_window", "WPA", None))
        self.radio_fake_ap_wpa2.setText(_translate("Main_window", "WPA2", None))
        self.textLabel3.setText(_translate("Main_window", "<b>Key in Hex</b> (Ex. aabbccddee) or <b>Empty</b>:", None))
        self.line_fake_ap_wep_key.setText(_translate("Main_window", "aabbccddee", None))
        self.groupBox13.setTitle(_translate("Main_window", "WPA/WPA2 types", None))
        self.radio_fake_ap_wep40.setText(_translate("Main_window", "WEP40", None))
        self.radio_fake_ap_tkip.setText(_translate("Main_window", "TKIP", None))
        self.radio_fake_ap_wrap.setText(_translate("Main_window", "WRAP", None))
        self.radio_fake_ap_ccmp.setText(_translate("Main_window", "CCMP", None))
        self.radio_fake_ap_wep104.setText(_translate("Main_window", "WEP104", None))
        self.groupBox7.setTitle(_translate("Main_window", "Options", None))
        self.check_fake_ap_adhoc_mode.setText(_translate("Main_window", "AdHoc mode", None))
        self.check_fake_ap_hidden_ssid.setText(_translate("Main_window", "Hidden SSID", None))
        self.check_fake_ap_no_broadcast.setText(_translate("Main_window", "Disable broadcast probes", None))
        self.check_fake_ap_all_probes.setText(_translate("Main_window", "Respond to all probes", None))
        self.button_fake_ap_start.setText(_translate("Main_window", "Start Fake Access Point", None))
        self.toolBox5.setItemText(self.toolBox5.indexOf(self.page12), _translate("Main_window", "Create Fake AP", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.TabPage3), _translate("Main_window", "Fake AP", None))
        self.groupBox1_5.setTitle(_translate("Main_window", "Normal cracking", None))
        self.textLabel10_4.setText(_translate("Main_window", "When you have enougth packets (>5000) you can try to decrypt the password.", None))
        self.button_crack_wep_aircrack.setText(_translate("Main_window", "Aircrack-ng - Decrypt WEP password", None))
        self.toolBox5_3.setItemText(self.toolBox5_3.indexOf(self.page13), _translate("Main_window", "WEP cracking", None))
        self.groupBox1_2_3.setTitle(_translate("Main_window", "Normal cracking", None))
        self.textLabel11_2_4.setText(_translate("Main_window", "Add you dictionary:", None))
        self.button_crack_wpa_aircrack.setText(_translate("Main_window", "Aircrack-ng - Crack WPA password", None))
        self.groupBox1_3_3.setTitle(_translate("Main_window", "Pyrit cracking", None))
        self.textLabel10_2_3.setText(_translate("Main_window", "<p align=\"center\">(For use it you need to install pyrit support)</p>", None))
        self.textLabel11_2_2_3.setText(_translate("Main_window", "Add you dictionary:", None))
        self.button_crack_wpa_pyrit.setText(_translate("Main_window", "Crack the password with pyrit", None))
        self.toolBox5_3.setItemText(self.toolBox5_3.indexOf(self.page22), _translate("Main_window", "WPA bruteforce cracking", None))
        self.groupBox1_3_3_2.setTitle(_translate("Main_window", "Rainbow Tables cracking", None))
        self.textLabel10_2_3_2.setText(_translate("Main_window", "<p align=\"center\">(Get rainbow tables from http://www.renderlab.net/projects/WPA-tables/ )</p>", None))
        self.textLabel11_2_2_3_2.setText(_translate("Main_window", "Add your rainbow tables file:", None))
        self.button_crack_wpa_rainbow_tables.setText(_translate("Main_window", "Crack the password with coWPAtty and Rainbow Tables", None))
        self.toolBox5_3.setItemText(self.toolBox5_3.indexOf(self.page3), _translate("Main_window", "WPA rainbow tables cracking", None))
        self.textLabel4_4_2_2_3.setText(_translate("Main_window", "<h2>Welcome in Cracking Control Panel</h2>", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.TabPage4), _translate("Main_window", "Cracking", None))
        self.textLabel4.setText(_translate("Main_window", "<h2>KEY Database</h2>", None))
        self.button_database_add.setText(_translate("Main_window", "Add entry", None))
        self.button_database_delete.setText(_translate("Main_window", "Delete entry", None))
        self.button_database_reload.setText(_translate("Main_window", "Reload", None))
        self.button_database_save.setText(_translate("Main_window", "Save", None))
        item = self.table_database.horizontalHeaderItem(0)
        item.setText(_translate("Main_window", "Essid", None))
        item = self.table_database.horizontalHeaderItem(1)
        item.setText(_translate("Main_window", "Bssid", None))
        item = self.table_database.horizontalHeaderItem(2)
        item.setText(_translate("Main_window", "Channel", None))
        item = self.table_database.horizontalHeaderItem(3)
        item.setText(_translate("Main_window", "Key", None))
        item = self.table_database.horizontalHeaderItem(4)
        item.setText(_translate("Main_window", "Ascii (not saved)", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.TabPage5), _translate("Main_window", "Database", None))
        self.textLabel14.setText(_translate("Main_window", "Authors:", None))
        self.textLabel16.setText(_translate("Main_window", "Emanuele Gentili - emgent@backtrack-linux.org<br>\n"
"Gerix.IT CSO and Partner<br>\n"
"http://www.gerix.it", None))
        self.textLabel17_2.setText(_translate("Main_window", "Emanuele Acri - crossbower@backtrack-linux.org\n"
"Gerix.IT Penetration Tester\n"
"http://www.backtrack.it/~crossbower/", None))
        self.label.setText(_translate("Main_window", "Porting to Qt4 freeExec", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.TabPage6), _translate("Main_window", "Credits", None))

